server :
  port : 8092




spring:
  application:
    name : activity-Service
  data:
    mongodb:
      # Change 'mongo' to 'mongodb' below
      uri : mongodb://localhost:27017/activity
      database : activity
  rabbitmq :
    host : localhost
    port : 5672
    username : guest
    password : guest




eureka :
  client :
    service-url :
      defaultZone : http://localhost:8761/eureka



rabbitmq:
  exchange :
    name : fitness.exchange
  queue :
    name : activity.queue
  routing :
    key : activity.tracking